version: '3.9'
services:
  chat-app-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # Expose Vscode debug port
    depends_on:
      - database

  # Database configuration

volumes:
  chat-app-database:
